# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "html5-utils-rails"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristian Mandrup"]
  s.date = "2012-08-28"
  s.description = "Time to use HTML5 and CSS3 now!!!"
  s.email = "kmandrup@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "html5-utils-rails.gemspec",
    "lib/html5-utils-rails.rb"
  ]
  s.homepage = "http://github.com/kristianmandrup/html5-utils-rails"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Package of gems containing polyfills for HTML 5 and CSS 3 functionality"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<pie-rails>, ["~> 1.1.0"])
      s.add_runtime_dependency(%q<flexlayout-rails>, ["~> 0.1.2"])
      s.add_runtime_dependency(%q<html5forms-rails>, ["~> 0.1.4"])
      s.add_runtime_dependency(%q<html5-now-rails>, ["~> 0.1.0"])
      s.add_runtime_dependency(%q<modernizr-rails>, ["~> 2.6.1"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.3"])
    else
      s.add_dependency(%q<pie-rails>, ["~> 1.1.0"])
      s.add_dependency(%q<flexlayout-rails>, ["~> 0.1.2"])
      s.add_dependency(%q<html5forms-rails>, ["~> 0.1.4"])
      s.add_dependency(%q<html5-now-rails>, ["~> 0.1.0"])
      s.add_dependency(%q<modernizr-rails>, ["~> 2.6.1"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, [">= 1.8.3"])
    end
  else
    s.add_dependency(%q<pie-rails>, ["~> 1.1.0"])
    s.add_dependency(%q<flexlayout-rails>, ["~> 0.1.2"])
    s.add_dependency(%q<html5forms-rails>, ["~> 0.1.4"])
    s.add_dependency(%q<html5-now-rails>, ["~> 0.1.0"])
    s.add_dependency(%q<modernizr-rails>, ["~> 2.6.1"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, [">= 1.8.3"])
  end
end

